Support using busybox instead of bash on Linux

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -45,21 +45,15 @@ runs:
       run: |
         set -eu
         if ! command -v bash >/dev/null; then
-          if grep -Eq '^ID=alpine' /etc/os-release; then
-            printf '::group::Install packages required for cache-cargo-install-action (bash)\n'
-            # NB: sync with apk_install in pre.sh
-            if command -v sudo >/dev/null; then
-              sudo apk --no-cache add bash
-            elif command -v doas >/dev/null; then
-              doas apk --no-cache add bash
-            else
-              apk --no-cache add bash
+          if command -v busybox >/dev/null; then
+            if test -n "${GITHUB_OUTPUT:-}"; then
+              busybox sh "${GITHUB_ACTION_PATH:?}/pre.sh"
+              printf 'shell=busybox\n' >>"${GITHUB_OUTPUT}"
+              exit
             fi
-            printf '::endgroup::\n'
-          else
-            printf '::error::cache-cargo-install-action requires bash\n'
-            exit 1
           fi
+          printf '::error::cache-cargo-install-action requires bash or busybox\n'
+          exit 1
         fi
         bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/pre.sh"
       shell: sh
@@ -118,12 +112,17 @@ runs:
         path: ${{ runner.os == 'Windows' && steps.pre-windows.outputs.path || steps.pre-unix.outputs.path }}
         key: ${{ runner.os == 'Windows' && steps.pre-windows.outputs.key || steps.pre-unix.outputs.key }}
     - name: Install ${{ inputs.tool }} (non-Windows)
-      run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/install.sh"
-      shell: bash
+      run: |
+        case "${CURRENT_SHELL}" in
+          busybox) busybox sh "${GITHUB_ACTION_PATH:?}/install.sh" ;;
+          *) bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/install.sh" ;;
+        esac
+      shell: sh
       env:
         # NB: Sync with Windows case.
         INPUT_ARGS: ${{ steps.pre-unix.outputs.args }}
         INPUT_TOOL: ${{ steps.pre-unix.outputs.tool }}
+        CURRENT_SHELL: ${{ steps.pre-unix.outputs.shell }}
       if: steps.cache.outputs.cache-hit != 'true' && runner.os != 'Windows'
     - name: Install ${{ inputs.tool }} (Windows)
       run: |
