Improve platform support

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -28,6 +28,27 @@ inputs:
 runs:
   using: composite
   steps:
+    - run: |
+        set -eu
+        if ! command -v bash >/dev/null; then
+          if grep -Eq '^ID=alpine' /etc/os-release; then
+            printf '::group::Install packages required for cache-cargo-install-action (bash)\n'
+            # NB: sync with apk_install in pre.sh
+            if command -v sudo >/dev/null; then
+              sudo apk --no-cache add bash
+            elif command -v doas >/dev/null; then
+              doas apk --no-cache add bash
+            else
+              apk --no-cache add bash
+            fi
+            printf '::endgroup::\n'
+          else
+            printf '::error::cache-cargo-install-action requires bash\n'
+            exit 1
+          fi
+        fi
+      shell: sh
+      if: runner.os	== 'Linux'
     - name: Pre Cache
       id: pre
       run: bash --noprofile --norc "${GITHUB_ACTION_PATH:?}/pre.sh"
